version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: codeigniter_web
    volumes:
      - ./codeigniter:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: codeigniter_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
